-- AlterTable
ALTER TABLE "BodyComposition" ADD COLUMN     "hipCm" DOUBLE PRECISION,
ADD COLUMN     "chestCm" DOUBLE PRECISION,
ADD COLUMN     "armCm" DOUBLE PRECISION,
ADD COLUMN     "thighCm" DOUBLE PRECISION;
